rl_policy:
  ros__parameters:
    actor_path: 'training_logs/ID_46/models/SAC_actor.pht'
    critic_path: 'training_logs/ID_46/models/SAC_critic.pht'
    algorithm: 'SAC'
    observation_mode: 'lidar_only'
