rl_policy:
  ros__parameters:
    actor_path: training_logs/good/models/TD3-280000_actor.pht
    critic_path: training_logs/good/models/TD3-280000_critic.pht
    algorithm: 'TD3'
    observation_mode: 'lidar_only'
