rl_policy:
  ros__parameters:
    actor_path: 'training_logs/ID_30/models/TD3AE_actor.pht'
    critic_path: 'training_logs/ID_30/models/TD3AE_critic.pht'
    algorithm: 'TD3AE'
    observation_mode: 'lidar_only'
