sim:
  ros__parameters:
    tracking: True
    algorithm: 'turn_and_drive'
    observation_mode: 'lidar_only'
    # environment: 'CarTrack'
    # track: 'multi_track'
    environment: 'CarTrack'
    track: 'austin_track'
    step_length: 0.1
    reward_range: 3
    collision_range: 0.2
    number_eval_episodes: 100
    max_steps: 3000