test:
  ros__parameters:
    environment: 'CarBeat'
    track: 'multi_track'
    max_steps_evaluation: 1000000
    actor_path: rl_logs/23_08_28_10:47:05/models/actor_checkpoint.pht
    critic_path: rl_logs/23_08_28_10:47:05/models/critic_checkpoint.pht
    max_steps: 300
    step_length: 0.25
    reward_range: 3.0
    collision_range: 0.2
    observation_mode: 'lidar_only'
