test:
  ros__parameters:
    environment: 'CarTrack'
    track: 'track_2'
    max_steps_evaluation: 1000000
    actor_path: rl_logs/23_07_06_01:46:43/models/actor_checkpoint.pht
    critic_path: rl_logs/23_07_06_01:46:43/models/critic_checkpoint.pht
    max_steps: 300
    step_length: 0.25
    reward_range: 2.0
    collision_range: 0.2